name: STLPluginHWChanges
version: '1.0'
main: org.mechSnow.sTLPluginHWChanges.STLPluginHWChanges
api-version: '1.21'
commands:
  testCMFN:
    description: "pizdes"
    usage: /testCMFN
  setcenter:
    description: "Установить центр барьера."
    usage: "/setcenter [x] [y] [z]"
  setradius:
    description: "Установить радиус барьера."
    usage: "/setradius <радиус>"
  expandradius:
    description: "Увеличить радиус барьера."
    usage: "/expandradius <добавочный_радиус>"
  getTemperature:
    description: "Показывает температуру игрока на action bar."
    usage: "/getTemperature"