name: STLPluginHWChanges
version: '1.0'
main: org.mechSnow.sTLPluginHWChanges.STLPluginHWChanges
api-version: '1.21'
commands:
  testCMFN:
    description: "I think test command."
    usage: /testCMFN
  setcenter:
    description: "Set center barrier."
    usage: "/setcenter [x] [y] [z]"
  setradius:
    description: "Set radius barrier."
    usage: "/setradius <radius>"
  expandradius:
    description: "Expand radius barrier."
    usage: "/expandradius <add_radius>"
  getTemperature:
    description: "Show temperature player on action bar."
    usage: "/getTemperature"